# Generated by Django 5.1.1 on 2024-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryinfo', '0002_alter_deliveryinfo_customer_alter_deliveryinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='wtsp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
