# Generated by Django 5.1.1 on 2024-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_reviews',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
