# Generated by Django 5.1.1 on 2024-11-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productsalehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSaleHistory',
        ),
    ]
